import type { ReviewData } from "./getReviewData";

export function getMockReviewData(submissionId: string): ReviewData {
  return {
    submissionId,
    status: "SUBMITTED",
    submittedAt: new Date(Date.now() - 2 * 60 * 60 * 1000),
    teacherComment: null,
    scorePercent: null,
    student: { id: "mock-student-1", name: "Иван Петров" },
    homework: {
      id: "mock-homework-1",
      title: "Контрольный вариант №3",
      classroomName: "11А",
      isVariant: true,
    },
    tasks: [
      {
        homeworkTaskId: "ht-1",
        taskId: "t-1",
        order: 1,
        examNumber: 1,
        title: null,
        condition: "Найдите значение выражения 3,12 : 2,6 − 0,8.",
        correctAnswer: "0,4",
        answerType: "NUMERIC",
        topicTitle: "Базовые вычисления",
        maxPoints: 1,
        answer: {
          id: "a-1",
          answer: "0,4",
          fileUrl: null,
          result: "CORRECT",
          score: 1,
          teacherComment: null,
          submittedAt: new Date(Date.now() - 2.5 * 60 * 60 * 1000),
          checkedAt: new Date(Date.now() - 2 * 60 * 60 * 1000),
        },
      },
      {
        homeworkTaskId: "ht-2",
        taskId: "t-2",
        order: 2,
        examNumber: 2,
        title: null,
        condition: "Прямоугольник имеет площадь 24 см². Ширина 4 см. Найдите длину.",
        correctAnswer: "6",
        answerType: "NUMERIC",
        topicTitle: "Геометрия: площади",
        maxPoints: 1,
        answer: {
          id: "a-2",
          answer: "8",
          fileUrl: null,
          result: "WRONG",
          score: 0,
          teacherComment: null,
          submittedAt: new Date(Date.now() - 2.5 * 60 * 60 * 1000),
          checkedAt: new Date(Date.now() - 2 * 60 * 60 * 1000),
        },
      },
      {
        homeworkTaskId: "ht-3",
        taskId: "t-3",
        order: 3,
        examNumber: 3,
        title: null,
        condition: "Решите уравнение: 2x + 5 = 13.",
        correctAnswer: "4",
        answerType: "NUMERIC",
        topicTitle: "Линейные уравнения",
        maxPoints: 1,
        answer: {
          id: "a-3",
          answer: "4",
          fileUrl: null,
          result: "CORRECT",
          score: 1,
          teacherComment: null,
          submittedAt: new Date(Date.now() - 2.5 * 60 * 60 * 1000),
          checkedAt: new Date(Date.now() - 2 * 60 * 60 * 1000),
        },
      },
      {
        homeworkTaskId: "ht-4",
        taskId: "t-4",
        order: 4,
        examNumber: 4,
        title: null,
        condition: "Найдите значение производной функции f(x) = x² в точке x = 3.",
        correctAnswer: "6",
        answerType: "NUMERIC",
        topicTitle: "Производная",
        maxPoints: 1,
        answer: null,
      },
      {
        homeworkTaskId: "ht-5",
        taskId: "t-5",
        order: 5,
        examNumber: 5,
        title: null,
        condition: "Найдите значение выражения log₂(8) + log₃(9).",
        correctAnswer: "5",
        answerType: "NUMERIC",
        topicTitle: "Логарифмы",
        maxPoints: 1,
        answer: {
          id: "a-5",
          answer: "5",
          fileUrl: null,
          result: "CORRECT",
          score: 1,
          teacherComment: null,
          submittedAt: new Date(Date.now() - 2.5 * 60 * 60 * 1000),
          checkedAt: new Date(Date.now() - 2 * 60 * 60 * 1000),
        },
      },
      {
        homeworkTaskId: "ht-6",
        taskId: "t-6",
        order: 6,
        examNumber: 6,
        title: null,
        condition: "Найдите наименьший угол в прямоугольном треугольнике, у которого катеты 3 и 4.",
        correctAnswer: "36,87",
        answerType: "NUMERIC",
        topicTitle: "Тригонометрия",
        maxPoints: 1,
        answer: {
          id: "a-6",
          answer: "37",
          fileUrl: null,
          result: "WRONG",
          score: 0,
          teacherComment: null,
          submittedAt: new Date(Date.now() - 2.5 * 60 * 60 * 1000),
          checkedAt: new Date(Date.now() - 2 * 60 * 60 * 1000),
        },
      },
      {
        homeworkTaskId: "ht-13",
        taskId: "t-13",
        order: 7,
        examNumber: 13,
        title: "Тригонометрическое уравнение",
        condition: "Решите уравнение: cos(2x) − cos(x) = 0. Запишите все решения и выберите те, что принадлежат отрезку [0; 3π].",
        correctAnswer: "",
        answerType: "TEXT",
        topicTitle: "Тригонометрические уравнения",
        maxPoints: 2,
        answer: {
          id: "a-13",
          answer: null,
          fileUrl: "/uploads/mock-solution-13.jpg",
          result: "PENDING",
          score: null,
          teacherComment: null,
          submittedAt: new Date(Date.now() - 2.5 * 60 * 60 * 1000),
          checkedAt: null,
        },
      },
      {
        homeworkTaskId: "ht-14",
        taskId: "t-14",
        order: 8,
        examNumber: 14,
        title: "Геометрическая задача",
        condition: "В прямоугольном треугольнике гипотенуза равна 10, один катет равен 6. Найдите площадь треугольника и длину медианы, проведённой к гипотенузе.",
        correctAnswer: "",
        answerType: "TEXT",
        topicTitle: "Геометрия: треугольники",
        maxPoints: 3,
        answer: {
          id: "a-14",
          answer: null,
          fileUrl: null,
          result: "PENDING",
          score: null,
          teacherComment: null,
          submittedAt: new Date(Date.now() - 2.5 * 60 * 60 * 1000),
          checkedAt: null,
        },
      },
    ],
  };
}
